### ISSUE TITLE
`require': no such file to load -- texticle/version (LoadError)

### ISSUE THREAD

**Issue by samullen** [texticle/texticle#23]
Upgraded to 2.1.0 this morning hoping that it will have partial word searching, but received the following error when trying to get in to the console:

```
/Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require': no such file to load -- texticle/version (LoadError)
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/texticle-2.1.0/lib/texticle.rb:3:in `<top (required)>'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/texticle-2.1.0/lib/texticle/rails.rb:2:in `<top (required)>'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler/runtime.rb:68:in `require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler/runtime.rb:66:in `each'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler/runtime.rb:66:in `block in require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler/runtime.rb:55:in `each'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler/runtime.rb:55:in `require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.1.5/lib/bundler.rb:119:in `require'
        from /Users/samullen/projects/run_title/config/application.rb:7:in `<top (required)>'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.2.11/lib/rails/commands.rb:39:in `require'
        from /Users/samullen/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.2.11/lib/rails/commands.rb:39:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

Gemfile line:
gem 'texticle',                   "~> 2.1.0", :require => 'texticle/rails'

I'm more than happy to help fix this, but I'm a little unsure where to begin.

Side note: where can I look to get partial word search working using Texticle?

Thanks

**Comment by benhamill** [comment]
Haven't looked at this deeply, but just a note that I edited the issue to make the stacktrace easier to see. Looking at it shortly. :smile:

**Comment by benhamill** [comment]
Yep. That's my bad. Somehow missed including the version.rb file in the gemspec. Patch release imminent. I'll post here when it's released. Good catch!

**Comment by samullen** [comment]
Glad you were able to fix it so easily and before the Monday rush. I didn't think to look in the gemspec.

Thanks, again, Ben.

**Comment by benhamill** [comment]
OK. Sorry for the broken release and the delay in fixing it. 2.1.1 is pushed now: https://rubygems.org/gems/texticle Thanks for catching this for us.

As for 'mount' and 'mountain': 2.1.0 introduced a `#fuzzy_search` method. I added a section to the README in 2.1.1 about it, but basically, it's what you're looking for. You'll have to make sure the trigram module is installed for your DB (there's a rake task provided by the gem, though it's untested on Heroku), but that should get you as close to what you're looking for as I think Postgres can get. Hope that helps. :smile:

**Comment by samullen** [comment]
Thanks, Ben. You're swell.
